/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.JOptionPane;
import seguridad.Interfaz;
import seguridad.MonoAlphabeticCipher;
import utility.Utility;

/**
 *
 * @author Oriana
 */
public class DescifrarFuerzaBruta extends javax.swing.JFrame {

    /**
     * Creates new form DescifrarFuerzaBruta
     */
    public DescifrarFuerzaBruta() {
        initComponents();
        Utility utility = new Utility(this);
        utility.centerOnScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        btn_volver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea_textoPlano1 = new javax.swing.JTextArea();
        lbl_textoPlano = new javax.swing.JLabel();
        b_descifrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_titulo.setText("Descifrar");

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        TextArea_textoPlano1.setColumns(20);
        TextArea_textoPlano1.setRows(5);
        jScrollPane2.setViewportView(TextArea_textoPlano1);

        lbl_textoPlano.setText("Texto cifrado");

        b_descifrar.setText("Descifrar");
        b_descifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_descifrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lbl_textoPlano)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_descifrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_textoPlano)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_volver)
                    .addComponent(b_descifrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String descifrar() {
        char cipherText[] = TextArea_textoPlano1.getText().toCharArray();
        char planeText[] = MensajeFuerzaBruta.planeText.toCharArray();
        StringBuilder result = new StringBuilder();
        int i;
        int j;
        int intentos = 0;
        JOptionPane.showMessageDialog(this, "Longitud de la cadena: " + cipherText.length);
        for (i = 0; i < cipherText.length; i++, intentos++) {
            JOptionPane.showMessageDialog(this, "Result: " + result);
            if (MensajeFuerzaBruta.planeText.equals(result.toString())) {
                return MensajeFuerzaBruta.planeText;
            }

            for (j = 0; j < 26; j++, intentos++) {
                //JOptionPane.showMessageDialog(this, "letra antes del cambio: " + cipherText[i]);
                cipherText[i] = MonoAlphabeticCipher.changeLetterE(cipherText[i], 1);
                //JOptionPane.showMessageDialog(this, "letra despues del cambio: " + cipherText[i]);

                if (cipherText[i] == planeText[i]) {
                    result.append(cipherText[i]);
                    //JOptionPane.showMessageDialog(this, "Agrego la letra al String Builder");
                    break;
                }
            }
        }
        //return "No se pudo descifrar";
        return result.toString();
    }
    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        Interfaz.getInterfaz(4).setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_volverActionPerformed

    private void b_descifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_descifrarActionPerformed
        //JOptionPane.showMessageDialog(this, "DALE QUE SÍ");
        System.out.println("Texto que hay que obtener> " + MensajeFuerzaBruta.planeText);
        JOptionPane.showMessageDialog(this, "El mensaje descifrado es: " + MonoAlphabeticCipher.fuerzaBruta(MensajeFuerzaBruta.planeText));

    }//GEN-LAST:event_b_descifrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DescifrarFuerzaBruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DescifrarFuerzaBruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DescifrarFuerzaBruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DescifrarFuerzaBruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DescifrarFuerzaBruta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea_textoPlano1;
    private javax.swing.JButton b_descifrar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_textoPlano;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
